/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, FinancialAccount } from "@prisma/client";

export class FinancialAccountServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.FinancialAccountCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.FinancialAccountCountArgs>
  ): Promise<number> {
    return this.prisma.financialAccount.count(args);
  }

  async financialAccounts<T extends Prisma.FinancialAccountFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.FinancialAccountFindManyArgs>
  ): Promise<FinancialAccount[]> {
    return this.prisma.financialAccount.findMany(args);
  }
  async financialAccount<T extends Prisma.FinancialAccountFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.FinancialAccountFindUniqueArgs>
  ): Promise<FinancialAccount | null> {
    return this.prisma.financialAccount.findUnique(args);
  }
  async createFinancialAccount<T extends Prisma.FinancialAccountCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.FinancialAccountCreateArgs>
  ): Promise<FinancialAccount> {
    return this.prisma.financialAccount.create<T>(args);
  }
  async updateFinancialAccount<T extends Prisma.FinancialAccountUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.FinancialAccountUpdateArgs>
  ): Promise<FinancialAccount> {
    return this.prisma.financialAccount.update<T>(args);
  }
  async deleteFinancialAccount<T extends Prisma.FinancialAccountDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.FinancialAccountDeleteArgs>
  ): Promise<FinancialAccount> {
    return this.prisma.financialAccount.delete(args);
  }
}
