/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FinancialAccountService } from "../financialAccount.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FinancialAccountCreateInput } from "./FinancialAccountCreateInput";
import { FinancialAccount } from "./FinancialAccount";
import { FinancialAccountFindManyArgs } from "./FinancialAccountFindManyArgs";
import { FinancialAccountWhereUniqueInput } from "./FinancialAccountWhereUniqueInput";
import { FinancialAccountUpdateInput } from "./FinancialAccountUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FinancialAccountControllerBase {
  constructor(
    protected readonly service: FinancialAccountService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FinancialAccount })
  @nestAccessControl.UseRoles({
    resource: "FinancialAccount",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFinancialAccount(
    @common.Body() data: FinancialAccountCreateInput
  ): Promise<FinancialAccount> {
    return await this.service.createFinancialAccount({
      data: data,
      select: {
        accountNumber: true,
        createdAt: true,
        id: true,
        text: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FinancialAccount] })
  @ApiNestedQuery(FinancialAccountFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FinancialAccount",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async financialAccounts(
    @common.Req() request: Request
  ): Promise<FinancialAccount[]> {
    const args = plainToClass(FinancialAccountFindManyArgs, request.query);
    return this.service.financialAccounts({
      ...args,
      select: {
        accountNumber: true,
        createdAt: true,
        id: true,
        text: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FinancialAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FinancialAccount",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async financialAccount(
    @common.Param() params: FinancialAccountWhereUniqueInput
  ): Promise<FinancialAccount | null> {
    const result = await this.service.financialAccount({
      where: params,
      select: {
        accountNumber: true,
        createdAt: true,
        id: true,
        text: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FinancialAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FinancialAccount",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFinancialAccount(
    @common.Param() params: FinancialAccountWhereUniqueInput,
    @common.Body() data: FinancialAccountUpdateInput
  ): Promise<FinancialAccount | null> {
    try {
      return await this.service.updateFinancialAccount({
        where: params,
        data: data,
        select: {
          accountNumber: true,
          createdAt: true,
          id: true,
          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FinancialAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FinancialAccount",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFinancialAccount(
    @common.Param() params: FinancialAccountWhereUniqueInput
  ): Promise<FinancialAccount | null> {
    try {
      return await this.service.deleteFinancialAccount({
        where: params,
        select: {
          accountNumber: true,
          createdAt: true,
          id: true,
          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
